In [11]:
import pandas as pd
import numpy as np

In [14]:
df_orders = pd.read_csv('data\Orders_and_shipments.csv',encoding='ISO-8859-1')
df_inventory = pd.read_csv('data\Inventory.csv')
df_fulfillment = pd.read_csv('data\Fulfillment.csv')

<>:1: SyntaxWarning: invalid escape sequence '\O'
<>:2: SyntaxWarning: invalid escape sequence '\I'
<>:3: SyntaxWarning: invalid escape sequence '\F'
<>:1: SyntaxWarning: invalid escape sequence '\O'
<>:2: SyntaxWarning: invalid escape sequence '\I'
<>:3: SyntaxWarning: invalid escape sequence '\F'
C:\Users\Aromal\AppData\Local\Temp\ipykernel_19428\884466402.py:1: SyntaxWarning: invalid escape sequence '\O'
  df_orders = pd.read_csv('data\Orders_and_shipments.csv',encoding='ISO-8859-1')
C:\Users\Aromal\AppData\Local\Temp\ipykernel_19428\884466402.py:2: SyntaxWarning: invalid escape sequence '\I'
  df_inventory = pd.read_csv('data\Inventory.csv')
C:\Users\Aromal\AppData\Local\Temp\ipykernel_19428\884466402.py:3: SyntaxWarning: invalid escape sequence '\F'
  df_fulfillment = pd.read_csv('data\Fulfillment.csv')

In [15]:
df_orders.head()

,Order ID,Order Item ID,Order YearMonth,Order Year,Order Month,Order Day,Order Time,Order Quantity,Product Department,Product Category,...,Customer Country,Warehouse Country,Shipment Year,Shipment Month,Shipment Day,Shipment Mode,Shipment Days - Scheduled,Gross Sales,Discount %,Profit
0,3535,8793,201502,2015,2,21,14:07,1,Fan Shop,Fishing,...,Mexico,Puerto Rico,2015,2,27,Standard Class,4,400,0.25,200
1,4133,10320,201503,2015,3,2,07:37,1,Fan Shop,Fishing,...,Brazil,Puerto Rico,2015,3,6,Standard Class,4,400,0.09,200
2,7396,18517,201504,2015,4,18,22:47,1,Fan Shop,Fishing,...,Mexico,Puerto Rico,2015,4,20,Standard Class,4,400,0.06,200
3,11026,27608,201506,2015,6,10,22:32,1,Fan Shop,Fishing,...,Denmark,Puerto Rico,2015,6,12,Standard Class,4,400,0.15,200
4,11026,27609,201506,2015,6,10,22:32,1,Fan Shop,Fishing,...,Denmark,Puerto Rico,2015,6,12,Standard Class,4,400,0.13,200

In [16]:
df_inventory.head()

,Product Name,Year Month,Warehouse Inventory,Inventory Cost Per Unit
0,Perfect Fitness Perfect Rip Deck,201712,0,0.69517
1,Nike Men's Dri-FIT Victory Golf Polo,201712,2,1.29291
2,O'Brien Men's Neoprene Life Vest,201712,0,0.56531
3,Nike Men's Free 5.0+ Running Shoe,201712,1,1.26321
4,Under Armour Girls' Toddler Spine Surge Runni,201712,0,1.47648

In [17]:
df_fulfillment.head()

,Product Name,Warehouse Order Fulfillment (days)
0,Perfect Fitness Perfect Rip Deck,8.3
1,Nike Men's Dri-FIT Victory Golf Polo,6.6
2,O'Brien Men's Neoprene Life Vest,5.5
3,Nike Men's Free 5.0+ Running Shoe,9.4
4,Under Armour Girls' Toddler Spine Surge Runni,6.3

Handling missing values

In [18]:
df_orders.isna().sum()

 Order ID                      0
 Order Item ID                 0
 Order YearMonth               0
 Order Year                    0
 Order Month                   0
 Order Day                     0
Order Time                     0
Order Quantity                 0
Product Department             0
Product Category               0
Product Name                   0
 Customer ID                   0
Customer Market                0
Customer Region                0
Customer Country               0
Warehouse Country              0
Shipment Year                  0
Shipment Month                 0
Shipment Day                   0
Shipment Mode                  0
 Shipment Days - Scheduled     0
 Gross Sales                   0
 Discount %                    0
 Profit                        0
dtype: int64

In [19]:
df_inventory.isna().sum()

Product Name               0
 Year Month                0
 Warehouse Inventory       0
Inventory Cost Per Unit    0
dtype: int64

In [20]:
df_fulfillment.isna().sum()

Product Name                            0
 Warehouse Order Fulfillment (days)     0
dtype: int64

In [21]:

df_orders.duplicated().sum()
     
df_inventory.duplicated().sum()
     
df_fulfillment.duplicated().sum()

0

In [22]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30871 entries, 0 to 30870
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0    Order ID                    30871 non-null  int64
 1    Order Item ID               30871 non-null  int64
 2    Order YearMonth             30871 non-null  int64
 3    Order Year                  30871 non-null  int64
 4    Order Month                 30871 non-null  int64
 5    Order Day                   30871 non-null  int64
 6   Order Time                   30871 non-null  object
 7   Order Quantity               30871 non-null  int64
 8   Product Department           30871 non-null  object
 9   Product Category             30871 non-null  object
 10  Product Name                 30871 non-null  object
 11   Customer ID                 30871 non-null  int64
 12  Customer Market              30871 non-null  object
 13  Customer Region              30871 non-null  object
 14  Customer Country             30871 non-null  object
 15  Warehouse Country            30871 non-null  object
 16  Shipment Year                30871 non-null  int64
 17  Shipment Month               30871 non-null  int64
 18  Shipment Day                 30871 non-null  int64
 19  Shipment Mode                30871 non-null  object
 20   Shipment Days - Scheduled   30871 non-null  int64
 21   Gross Sales                 30871 non-null  int64
 22   Discount %                  30871 non-null  object
 23   Profit                      30871 non-null  int64
dtypes: int64(14), object(10)
memory usage: 5.7+ MB

In [23]:
df_inventory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4200 entries, 0 to 4199
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product Name             4200 non-null   object
 1    Year Month              4200 non-null   int64
 2    Warehouse Inventory     4200 non-null   int64
 3   Inventory Cost Per Unit  4200 non-null   float64
dtypes: float64(1), int64(2), object(1)
memory usage: 131.4+ KB

In [24]:
df_fulfillment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 2 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Product Name                          118 non-null    object
 1    Warehouse Order Fulfillment (days)   118 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.0+ KB

In [25]:
# using strip fn removing unwanted spaces from columns name
dataframes = [df_inventory, df_orders, df_fulfillment]

for df in dataframes:
  df.columns = df.columns.str.strip()

In [26]:
df_orders.columns

Index(['Order ID', 'Order Item ID', 'Order YearMonth', 'Order Year',
       'Order Month', 'Order Day', 'Order Time', 'Order Quantity',
       'Product Department', 'Product Category', 'Product Name', 'Customer ID',
       'Customer Market', 'Customer Region', 'Customer Country',
       'Warehouse Country', 'Shipment Year', 'Shipment Month', 'Shipment Day',
       'Shipment Mode', 'Shipment Days - Scheduled', 'Gross Sales',
       'Discount %', 'Profit'],
      dtype='object')

In [27]:
df_inventory.columns

Index(['Product Name', 'Year Month', 'Warehouse Inventory',
       'Inventory Cost Per Unit'],
      dtype='object')

In [28]:
df_fulfillment.columns

Index(['Product Name', 'Warehouse Order Fulfillment (days)'], dtype='object')

In [29]:
df_orders['Discount %'].sample(30)

6732      0.09
1380      0.01
23487     0.15
21727     0.16
16924     0.13
25979     0.16
19169      -
29251     0.16
8923      0.02
4849      0.06
29441     0.07
8400      0.18
15436     0.03
21352     0.13
26275     0.12
27765     0.09
8307      0.04
7299      0.12
11659     0.12
26336     0.02
19732      0.1
16331     0.04
29566     0.16
4307      0.01
27169      -
21785     0.12
3127      0.13
30811      0.2
12306     0.12
5627      0.04
Name: Discount %, dtype: object

In [30]:
# Convert the '-' values to 0 in the 'Discount %' column and then change the data type from object to float
df_orders['Discount %'] = df_orders['Discount %'].replace('  -  ', 0).astype(float)

In [31]:
df_orders.columns

Index(['Order ID', 'Order Item ID', 'Order YearMonth', 'Order Year',
       'Order Month', 'Order Day', 'Order Time', 'Order Quantity',
       'Product Department', 'Product Category', 'Product Name', 'Customer ID',
       'Customer Market', 'Customer Region', 'Customer Country',
       'Warehouse Country', 'Shipment Year', 'Shipment Month', 'Shipment Day',
       'Shipment Mode', 'Shipment Days - Scheduled', 'Gross Sales',
       'Discount %', 'Profit'],
      dtype='object')

In [32]:
# Make new columns: Order Datetime and Shipment Datetime
df_orders['Order Datetime'] = pd.to_datetime(df_orders['Order Year'].astype(str) + '-' + df_orders['Order Month'].astype(str) + '-' + df_orders['Order Day'].astype(str) + ' ' + df_orders['Order Time'])
df_orders['Shipment Datetime'] = pd.to_datetime(df_orders['Shipment Year'].astype(str) + '-' + df_orders['Shipment Month'].astype(str) + '-' + df_orders['Shipment Day'].astype(str))

# Displaying the result
df_orders[['Order Datetime', 'Shipment Datetime']].head()

       Order Datetime Shipment Datetime
0 2015-02-21 14:07:00        2015-02-27
1 2015-03-02 07:37:00        2015-03-06
2 2015-04-18 22:47:00        2015-04-20
3 2015-06-10 22:32:00        2015-06-12
4 2015-06-10 22:32:00        2015-06-12

In [33]:
df_orders.drop(columns=['Order Year', 'Order Month', 'Order Day', 'Order Time',
                        'Shipment Year', 'Shipment Month', 'Shipment Day'], inplace=True)

In [34]:
df_orders['Customer Country'].unique()

array(['Mexico', 'Brazil', 'Denmark', 'Netherlands', 'Germany', 'China',
       'Indonesia', 'Pakistan', 'India', 'USA', 'Hungary', 'Sudan',
       'Democratic Republic of Congo', 'Poland', 'Togo', 'Guatemala',
       'Panama', 'Chile', 'France', 'Sweden', 'Dominican\xa0Republic',
       'Venezuela', 'South Korea', 'Madagascar', 'Iran', 'Cuba',
       'Nicaragua', 'United Kingdom', 'Afghanistan', 'Singapore',
       'Morocco', 'Spain', 'Niger', 'Turkey', 'South Africa', 'Iraq',
       'Honduras', 'Italy', 'Australia', 'Cote d\x92Ivoire', 'Croatia',
       'Ecuador', 'Syria', 'Haiti', 'Bangladesh', 'Argentina', 'Romania',
       'El Salvador', 'Vietnam', 'Japan', 'Nigeria', 'Belarus',
       'Uzbekistan', 'Egypt', 'Albania', 'Georgia', 'Cameroon',
       'Colombia', 'New zealand', 'Canada', 'Thailand', 'Senegal',
       'Russia', 'Perú', 'Algeria\xa0', 'Ukraine', 'Belgium',
       'Philippines', 'Austria', 'Uruguay', 'Malaysia', 'Hong Kong',
       'Saudi Arabia', 'Switzerland', 'Ireland', 'Bulgaria', 'Zambia',
       'Jamaica', 'Ghana', 'Yemen', 'Norway', 'Tanzania', 'Kazakhstan',
       'Libya', 'Trinidad and Tobago', 'Finland', 'Portugal', 'Kenya',
       'Jordania', 'Bolivia', 'Gabon', 'Angola', 'Myanmar', 'Mali', 'UAE',
       'Bosnia and Herzegovina', 'Guinea', 'Cambodia', 'Papua New Guinea',
       'Rwanda', 'Israel\xa0', 'Guyana', 'Somalia', 'Barbados',
       'Guadalupe', 'Kyrgyzstan', 'Benín', 'Tunisia', 'Lithuania',
       'Montenegro', 'Costa Rica', 'Mozambique', 'Sri Lanka', 'Taiwan',
       'Czech Republic (Czechia)', 'Lesotho', 'Mongolia', 'Macedonia',
       'Zimbabwe', 'Liberia', 'Liban', 'Guinea-Bissau', 'Estonia',
       'Azerbaijan', 'Moldova', 'Republic of Congo', 'Gambia',
       'Mauritania', 'Belize', 'Qatar', 'Sierra Leona', 'Slovakia',
       'Martinique', 'Uganda', 'Namibia', 'Paraguay', 'Oman',
       'French Guiana', 'Nepal'], dtype=object)

In [35]:
#replace the special characters in the Customer Country column
df_orders['Customer Country'] = df_orders['Customer Country'].replace({
    'Dominican\xa0Republic': 'Dominican Republic',
    'Cote d\x92Ivoire': 'Cote d Ivoire', # Added a comma at the end of this line
    'Perú': 'Peru',
    'Algeria\xa0': 'Algeria',
    'Israel\xa0':'Israel',
    'Benín': 'Benin'
})
df_orders['Customer Country'].unique()

array(['Mexico', 'Brazil', 'Denmark', 'Netherlands', 'Germany', 'China',
       'Indonesia', 'Pakistan', 'India', 'USA', 'Hungary', 'Sudan',
       'Democratic Republic of Congo', 'Poland', 'Togo', 'Guatemala',
       'Panama', 'Chile', 'France', 'Sweden', 'Dominican Republic',
       'Venezuela', 'South Korea', 'Madagascar', 'Iran', 'Cuba',
       'Nicaragua', 'United Kingdom', 'Afghanistan', 'Singapore',
       'Morocco', 'Spain', 'Niger', 'Turkey', 'South Africa', 'Iraq',
       'Honduras', 'Italy', 'Australia', 'Cote d Ivoire', 'Croatia',
       'Ecuador', 'Syria', 'Haiti', 'Bangladesh', 'Argentina', 'Romania',
       'El Salvador', 'Vietnam', 'Japan', 'Nigeria', 'Belarus',
       'Uzbekistan', 'Egypt', 'Albania', 'Georgia', 'Cameroon',
       'Colombia', 'New zealand', 'Canada', 'Thailand', 'Senegal',
       'Russia', 'Peru', 'Algeria', 'Ukraine', 'Belgium', 'Philippines',
       'Austria', 'Uruguay', 'Malaysia', 'Hong Kong', 'Saudi Arabia',
       'Switzerland', 'Ireland', 'Bulgaria', 'Zambia', 'Jamaica', 'Ghana',
       'Yemen', 'Norway', 'Tanzania', 'Kazakhstan', 'Libya',
       'Trinidad and Tobago', 'Finland', 'Portugal', 'Kenya', 'Jordania',
       'Bolivia', 'Gabon', 'Angola', 'Myanmar', 'Mali', 'UAE',
       'Bosnia and Herzegovina', 'Guinea', 'Cambodia', 'Papua New Guinea',
       'Rwanda', 'Israel', 'Guyana', 'Somalia', 'Barbados', 'Guadalupe',
       'Kyrgyzstan', 'Benin', 'Tunisia', 'Lithuania', 'Montenegro',
       'Costa Rica', 'Mozambique', 'Sri Lanka', 'Taiwan',
       'Czech Republic (Czechia)', 'Lesotho', 'Mongolia', 'Macedonia',
       'Zimbabwe', 'Liberia', 'Liban', 'Guinea-Bissau', 'Estonia',
       'Azerbaijan', 'Moldova', 'Republic of Congo', 'Gambia',
       'Mauritania', 'Belize', 'Qatar', 'Sierra Leona', 'Slovakia',
       'Martinique', 'Uganda', 'Namibia', 'Paraguay', 'Oman',
       'French Guiana', 'Nepal'], dtype=object)

In [36]:
df_orders['Order Processing Time'] = (df_orders['Shipment Datetime'] - df_orders['Order Datetime']).dt.days
df_orders['Order Processing Time'] = df_orders['Order Processing Time'].apply(lambda x: 0 if x == -1 else x)

df_orders.sample(5)

,Order ID,Order Item ID,Order YearMonth,Order Quantity,Product Department,Product Category,Product Name,Customer ID,Customer Market,Customer Region,Customer Country,Warehouse Country,Shipment Mode,Shipment Days - Scheduled,Gross Sales,Discount %,Profit,Order Datetime,Shipment Datetime,Order Processing Time
27495,57613,144115,201706,5,Golf,Women's Apparel,Nike Men's Dri-FIT Victory Golf Polo,9278,LATAM,Central America,Honduras,Puerto Rico,Same Day,3,250,0.18,125,2017-06-09 13:49:00,2017-08-16,67
19485,61238,153174,201508,1,Fan Shop,Water Sports,Pelican Sunstream 100 Kayak,2831,LATAM,Central America,Mexico,USA,Standard Class,4,200,0.13,100,2015-08-23 09:28:00,2015-08-27,3
3534,35545,88772,201605,1,Fan Shop,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,549,North America,East of USA,USA,USA,Standard Class,4,300,0.17,150,2016-05-28 18:01:00,2016-06-03,5
7109,19878,49680,201511,1,Apparel,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,7043,Europe,Northern Europe,United Kingdom,USA,Standard Class,4,130,0.06,65,2015-11-03 20:14:00,2015-11-05,1
21920,35638,89000,201606,5,Footwear,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,10422,North America,South of USA,USA,USA,First Class,1,500,0.16,245,2016-06-04 05:13:00,2015-11-26,-192